name: JJTS Films
favicon: null
layout_spectrum: 0.5635207260493189
typography_spectrum: 0.10935
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#08050c'
    - '#00ffff'
    - '#ef7b30'
    - '#ffff0a'
  brandStrength: 0.7404394228942692
  lightness: 0.9555732836015522
  saturation: 0.27138819987885654
  rhythmicContrast: 0.1486531647387892
purpose: []
