name: JJTS Films
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73421168-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5a5c50'
    - '#d3d2cd'
    - '#fc403c'
    - '#790808'
  brandStrength: 0.7404394228942692
  lightness: 0.9555732836015522
  saturation: 0.75
  rhythmicContrast: 0.1486531647387892
purpose: []
