name: JJTS Films
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffff01'
    - '#ff9200'
    - '#811f00'
    - '#ff4500'
  brandStrength: 0.7404394228942692
  lightness: 0.9555732836015522
  saturation: 0.75
  rhythmicContrast: 0.1486531647387892
purpose: []
